/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNearbyRouteImport } from './routes/api/nearby'
import { Route as ApiNetworkRouteImport } from './routes/api/network'
import { Route as ApiOnlineRouteImport } from './routes/api/online'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiStorageRouteImport } from './routes/api/storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearbyRoute = ApiNearbyRouteImport.update({
  id: '/api/nearby',
  path: '/api/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkRoute = ApiNetworkRouteImport.update({
  id: '/api/network',
  path: '/api/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnlineRoute = ApiOnlineRouteImport.update({
  id: '/api/online',
  path: '/api/online',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRoute = ApiStorageRouteImport.update({
  id: '/api/storage',
  path: '/api/storage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/nearby': typeof ApiNearbyRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/online': typeof ApiOnlineRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/storage': typeof ApiStorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/nearby': typeof ApiNearbyRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/online': typeof ApiOnlineRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/storage': typeof ApiStorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/nearby': typeof ApiNearbyRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/online': typeof ApiOnlineRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/storage': typeof ApiStorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/nearby'
    | '/api/network'
    | '/api/online'
    | '/api/rtc'
    | '/api/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/nearby'
    | '/api/network'
    | '/api/online'
    | '/api/rtc'
    | '/api/storage'
  id:
    | '__root__'
    | '/'
    | '/api/nearby'
    | '/api/network'
    | '/api/online'
    | '/api/rtc'
    | '/api/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiNearbyRoute: typeof ApiNearbyRoute
  ApiNetworkRoute: typeof ApiNetworkRoute
  ApiOnlineRoute: typeof ApiOnlineRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiStorageRoute: typeof ApiStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nearby': {
      id: '/api/nearby'
      path: '/api/nearby'
      fullPath: '/api/nearby'
      preLoaderRoute: typeof ApiNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network': {
      id: '/api/network'
      path: '/api/network'
      fullPath: '/api/network'
      preLoaderRoute: typeof ApiNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/online': {
      id: '/api/online'
      path: '/api/online'
      fullPath: '/api/online'
      preLoaderRoute: typeof ApiOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage': {
      id: '/api/storage'
      path: '/api/storage'
      fullPath: '/api/storage'
      preLoaderRoute: typeof ApiStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiNearbyRoute: ApiNearbyRoute,
  ApiNetworkRoute: ApiNetworkRoute,
  ApiOnlineRoute: ApiOnlineRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiStorageRoute: ApiStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
